### ISSUE TITLE
Missing decrease retry counter leads to "endless-loop-ish" desaster scenario  

### ISSUE THREAD

**Issue by nitram509** [contentful/contentful-sdk-core#103]
Hi,

we're using Contentful JS SDK 4.6.2 and face an issue when we were close to the API limit.
In our analysis, we found in these lines of code
https://github.com/contentful/contentful-sdk-core/blob/1ba2d2e2cab09d38f3f73d2058fc4ea83ab2ff9e/lib/rate-limit.js#L73
that there's an infinite number of retries happen, in case of API limit reached.

I do expect that the number of retries is limited, in order to avoid [thundering herd problem](https://en.wikipedia.org/wiki/Thundering_herd_problem).
(as it is implemented in case of 50x errors)

Here's some context of our analysis.
Our API usage is quite regular, but on a specific Friday, it "exploded".
![Screenshot 2020-09-03 at 10 11 25](https://user-images.githubusercontent.com/1189394/92485222-f4355a80-f1ea-11ea-9110-fca378e3c6c0.png)
We have the most traffic during business hours - it's still quite small, since this is a NON-PROD environment, mostly used for developer and automated tests - hence the small and regular usage (besides Friday).

We did check the logs, and realized a large spike in these error messages from our portal, caused by Contentful (SDK).
We only had the chance to shut down our service, which solved the problem.
![Screenshot 2020-09-04 at 10 40 05 copy](https://user-images.githubusercontent.com/1189394/92485633-7cb3fb00-f1eb-11ea-8661-65015d9d32f5.png)

Interestingly, this is a PRE-PROD environment and we checked the inbound traffic as well as (thanks to Contentful support) the source IPs from our API request. We can exclude any (D)DOS attack, but rather believe, that our parallel running web-nodes (ca. 6 at the time) did suffer from the thundering herd problem and were not able to recover, because of the infinite retries. We also seem rate limit warnings on a bi-daily basis, but typically can recover from that after a few seconds.

**Comment by matthew-contentful** [comment]
Hello nitram509,

The unlimited retry behavior is expected. Each subsequent request takes longer to avoid calling too often. Perhaps consider limiting concurrency in your application?

Thanks, Matthew

**Comment by nitram509** [comment]
Hi Matthew

thank you for your quick reply.

Unfortunately, I'm not getting, why this is expected, because in my scenario it's clearly not.
May I ask, why this is expected, from your point of view?

To shed some more light on my/our context.
The 6 web nodes we need for high availability reasons and load distribution, so I can't reduce them.
As you can see from the above graph, our API usage is relatively low on a regular day.
We use contentful's dictionary and page content to render HTML on the server-side.
This is because of SEO optimization and we can't switch to client-side rendering.
I have zero chance to reduce the level of concurrency, as this purely reflects the number of users we have.
The jitter (which is implemented as ```1500 + random*200``` milliseconds), is clearly not enough to avoid such a situation,
as our above context and logs prove.
One idea we have is to cache contentful's responses, but that leads to other discussions, you're probably familiar with.

Anticipating you have some other use case in mind, is there may be a chance,
to have an optional configuration flag, so we could limit the number of retries in such a scenario?

/cc @matthew-contentful 

Best regards
Martin
