### ISSUE TITLE
Why is "lodash" fully imported?

### ISSUE THREAD

**Issue by pfumagalli** [contentful/contentful-sdk-core#220]
As far as I can see, version 6.9.1 imports the whole `lodash` while only uses `isPlainObject` in the code.

In my build, manually editing `node_modules/contentful-sdk-core/dist/index.es-modules.js` and importing `isPlainObject` from `lodash/isPlainObject.js` reduces my build size of approximately 73 Kb (in my case approx ~20% of my whole app)

It seems quite significant, as the wasted import is definitely bigger than the rest of all of the Contentful/Axios client combined.

Need a PR?

**Comment by marcolink** [comment]
@pfumagalli thanks for reporting this! 
Feel free to review the PR we created for that: #223
