### ISSUE TITLE
Axios Type error - Cannot use latest contentful-management with `contentful-sdk-core`

### ISSUE THREAD

**Issue by Crizzooo** [contentful/contentful-sdk-core#275]
## The Issue

We are trying to use `contentful-management@10.6.3`. This package depends on `"contentful-sdk-core": "^7.0.1"`.

When running our type check, we hit this error:

```
node_modules/contentful-sdk-core/dist/types/types.d.ts:1:10 - error TS2614: Module '"axios"' has no exported member 'AxiosRequestHeaders'. Did you mean to use 'import AxiosRequestHeaders from "axios"' instead?

1 import { AxiosRequestHeaders } from 'axios';
           ~~~~~~~~~~~~~~~~~~~
```

<img width="884" alt="Screen Shot 2022-06-16 at 6 57 25 PM" src="https://user-images.githubusercontent.com/18145174/174191731-862add54-0eb8-4a35-9c68-9c1308e7208b.png">

Using `skipLibCheck` is not currently an option for us.

## Theories on the cause
- `contentful-management` lists its axios dependency as a real dependency. This installs the correct version of axios inside of `contentful-management`. However, `contentful-sdk-core` only lists a dev dependency, so `axios` is not installed inside of that module. The rest of our applications resolves to a lower version of axios in the top level `node_modules` that does not export this type. As a result, `contentful-sdk-core` uses repo axios version and fails the typecheck in `node_modules/contentful-sdk-core/dist/types/types.d.ts`.

here's a visual of the output from `npm ls axios`

```
├─┬ @slack/web-api@6.3.0
│ └── axios@0.21.4
├─┬ @slack/webhook@5.0.3
│ └── axios@0.19.2
├─┬ analytics-node@5.1.2
│ └── axios@0.21.4  deduped
├─┬ contentful-management@10.6.3
│ └── axios@0.27.2
├─┬ plaid@9.1.0
│ └── axios@0.21.1
└─┬ twilio@3.76.1
  └── axios@0.26.1
```

## Possible Solutions
Contentful-sdk-core could list this axios version as an actual dependency, instead of a dev dependency.  This will allow its types to resolve to the correct version.

Alternatively, if these types arent being used by consumers of the application, could you just remove the import of the types from axios?

This is currently blocking our ability to adopt Contentful on our backend.

**Comment by Crizzooo** [comment]
I can confirm that by moving the axios installation to be an actual dependency of `contentful-sdk-core`, I get the following result and can build the application.

Should I file a PR to move axios as a direct dependency?

```
$ npm ls axios
├─┬ @slack/web-api@6.3.0
│ └── axios@0.21.4
├─┬ @slack/webhook@5.0.3
│ └── axios@0.19.2
├─┬ analytics-node@5.1.2
│ └── axios@0.21.4  deduped
├─┬ contentful-management@10.6.3
│ ├── axios@0.27.2
│ └─┬ contentful-sdk-core@7.0.2
│   └── axios@0.26.1
├─┬ plaid@9.1.0
│ └── axios@0.21.1
└─┬ twilio@3.76.1
  └── axios@0.26.1
```

**Comment by Crizzooo** [comment]
We are currently resolving this by running a postinstall hook to install axios inside of this package's node_module folder.

Still would like a more permanent solution, or some insight as to why this problem exists for us

**Comment by andreascful** [comment]
Thank you for the report.
Since contentful-sdk-core only uses the types of axios in its code and is no actual implementation of a axios feature, it should be fine that it's used as a dev dependency. 
However, the library requires a minimum axios version of 0.26.0. It seems that you are using an older version of axios that does not yet provide the types we are using. Would it be possible for you to update your axios dependency in order to get those types?

**Comment by marcolink** [comment]
Closing this for now as there hasn't been any activity in a while and we assume
you were able to solve it at hand.

But feel free to reach out again if you have more questions.
