### ISSUE TITLE
How to handle rate limiting

### ISSUE THREAD

**Issue by barryskal** [contentful/contentful-sdk-core#49]
Not sure if this should be asked here, or in [contentful-managmenet.js](https://github.com/contentful/contentful-management.js). How exactly is rate limiting handled by the client? For example, if I have the following code: 
```
  const space = await client.getSpace(CONTENTFUL_SPACE_ID)
  return space.createEntry(contentType, entry)
```
I can see the following error in the log:
`[warning] Connection error occurred. Waiting for 1981 ms before retrying...`

Note that this entry creation is amongst several updates/creates all happening very close to each other because I am updating a type which has many referenced types. So rate limiting of my requests is not surprising. What is unusual though is that the promise for `createEntry` resolves with the `space` object rather than the new `entry` object. 

Is the client meant to be handling rate limiting errors or is it supposed to be taken care of internally by the library?

**Comment by barryskal** [comment]
I've resolved my issues. It turns out that the value of `contentType` I was passing in was undefined and the error returned was that the `X-Contentful-Content-Type` header had no value to be set. Although, the above issue still stands, the API call silently failed and I had to update the library manually to log the error. Perhaps an empty response should throw an exception?

**Comment by axe312ger** [comment]
Hey Barry,

first of all: Yeah, the lib handles rate limiting internally and will delay your promise until it could make the request. You can disable this behaviour here: https://github.com/contentful/contentful-management.js#retryonerror-default-true

How did you end up with a empty response? If the status code is between 500 and 600 it will retry 5 times and then throw the error.

`What is unusual though is that the promise for createEntry resolves with the space object rather than the new entry object.`
This sounds like a bug, can you please provide code to reproduce this issue?

Thanks a lot,
Benedikt

**Comment by barryskal** [comment]
No problem @axe312ger this is how I can reproduce it.
```
export async function testThing() {
  const space = await client.getSpace(CONTENTFUL_SPACE_ID)
  const contentType = undefined
  const entry = {}
  const createdEntry = await space.createEntry(contentType, entry)
  return createdEntry
}
```

The value returned from `testThing` will be the space object

**Comment by barryskal** [comment]
Note that I put the following line [here](https://github.com/contentful/contentful-sdk-core/blob/master/lib/rate-limit.js#L20)

`console.log('****Error', error)`

This produced the log, `****Error Error: "value" required in setHeader("X-Contentful-Content-Type", value)`

I have also encountered another bug when my requests are rate limited. I first get the following warning, `[warning] Rate limit error occurred. Waiting for 1557 ms before retrying...`
Then my log statement above is triggered on the library's next attempt and the following message is produced, 
`****Error TypeError: self.agent.addRequest is not a function`
The next warning is: 
`[warning] Connection error occurred. Waiting for 1942 ms before retrying...`
and this results in a contentful response that shows a 404 error for the entry type that I am querying for. Even though it exists in the contentful UI

**Comment by axe312ger** [comment]
Thank you Barry! I will investigate and come back to you :)
