### ISSUE TITLE
Better handling for connection/authentication failures

### ISSUE THREAD

**Issue by sgb-io** [contentful/contentful-sdk-core#5]
Sometimes I want to test my application by intentionally mis-configuring the Contentful adapter I have composed (which uses contentful.js). (Use case: ensure my application can survive mis-configuration mistakes or Contentful downtime)

Unless I'm mistaken, there doesn't seem to be an easy way to handle this from `contentful.js`. In particular it seems to accept any host, so will result in timeouts.

Keen to know what your thoughts are on how to handle this better. Improving this problem may be a case of (a) reinforcing usage of `createClient` and (b) authenticating with Contentful and introducing an "authenticated" state

**Comment by pyramidium** [comment]
Maybe take a look at the management api? https://github.com/contentful/contentful-management.js?files=1

**Comment by Khaledgarbaya** [comment]
`Contentful.js` is tended only for delivering content and no authentication involved, the Authentication is done Already in the web app, that's why you are seeing the `token` in the API section. So you need to provide the correct configuration for it, because that's what it expect.
If you want to do the authentication yourself I would recommend that you check [contentful-management.js](https://github.com/contentful/contentful-management.js)

**Comment by sgb-io** [comment]
> Contentful.js is tended only for delivering content and no authentication involved

Technically there **is** authentication: you need to check my `accessToken`. Sure, it's just for delivery only, but this data should only be given to authenticated users.

I can see that `contentful-management.js` solves this problem by having error handlers for each request, and an application can easily deal with it using `client.getSpace`:

```javascript
client.getSpace('spaceId')
.then((space) => {})
.catch((error) => {
 // handle authentication (eg bad access token) or connection (eg timeout) problems here
})
```

However, I'm not sure of a good way to port the same solution over to `Contentful.js`. All I can think of is doing `getEntry` on a specific item?

Also - using the management API can solve some use cases but doesn't fit right now if you want read-only access (as far as I can tell, you cannot configure an application to have read-only or fine-grained permissions).

**Comment by Khaledgarbaya** [comment]
There is also an errorHandler in `Contentful.js` attached to every request [here](https://github.com/contentful/contentful.js/blob/master/lib/create-contentful-api.js#L129) for example 

you can do

```js
client.Entry('spaceId')
.then((entry) => {})
.catch((error) => {
 // check the detail of the error
})
```

**Comment by Khaledgarbaya** [comment]
I am closing this issue right now, please feel free to add a new one if you have any issue/questions
