### ISSUE TITLE
Custom hosts are matched against a very strict regex

### ISSUE THREAD

**Issue by Soliah** [contentful/contentful-sdk-core#56]
In Contentful.js there is an option to specify a proxy `host` as described here: https://contentful.github.io/contentful.js/contentful/5.1.3/contentful.html#.createClient

However there is a test against this provided host in this repo here: https://github.com/contentful/contentful-sdk-core/blob/master/lib/create-http-client.js#L9

This regex does not match things like the following:

- localhost
- localhost:4444

This makes it very difficult to do testing against a locally running version of a proxy. Can this be changed to be a bit more lenient?

**Comment by axe312ger** [comment]
Hey Soliah,

yeah we should make this possible, thank you for raising this ticket :)

I may have a look soon, any suggestions from your side what to transform the regex into?

Best,
Benedikt

**Comment by dpfavand** [comment]
Currently running into this issue as well. It looks like you would need to remove the requirement for a `.` between two strings (`sub.domain`), and make it optional.

**Comment by phoebeschmidt** [comment]
hey @dpfavand, PRs are welcome! Sorry we haven't gotten to this sooner.
