### ISSUE TITLE
Window is undefined when using SSR

### ISSUE THREAD

**Issue by jncampbell** [contentful/contentful-sdk-core#59]
I’m using this package in an application with react on the front end, rails on the backend and hooked up via react-on-rails. 

Everything works fine on the client but when I run my server build, I receive a ‘window is undefined’ error. Following the stacktrace, it seems the culprit is the use of ‘window’ in the getBrowserOS function of the lib/get-user-agent.js file. The error goes away if I use the more common method of if (typeof window === “undefined”){}. 

I have a PR ready but I want to make sure I’m not missing something before opening it.

**Comment by axe312ger** [comment]
This lib is not intended to be used directly in projects, what is your use case to directly using it?

We do some webpack magic to polyfill/stub the window object etc. in the node bundle of the SDKs since our http client, axios, can also be very nasty.


A `typeof window === “undefined”` wont fix it since window might be `null` in some cases, but a combination of typeof and our old check might be helping.

But first things first, what are you doing with it? Maybe we can find another way to solve your issue :)

Best,
Benedikt

**Comment by jncampbell** [comment]
I'm not using the lib directly in projects. I'm using the `contentful` npm package. The stacktrace pointed me to that package first, but ultimately pointed to the `contentful-sdk-core`s `getBrowserOS` function, so I figured it made sense to open the issue on this package. Was I mistaken in that assumption? 

Also, just to note, I'm using `contentful@5.1.3`

**Comment by axe312ger** [comment]
Ahh here we go :)

We supply multiple versions and list them in the respective field in the package.json:
https://github.com/contentful/contentful.js/blob/master/package.json#L6-L9

Try to require like this to enforce the node version on your server: 

```js
const contentful = require('contentful/dist/contentful.node.js')
```

Does this help?

If not, check if you can control which main field from the package.json is used for SSR. It should be `main` for SSR and `browser` or `module` for browser.

With webpack, you control it with this config: https://webpack.js.org/configuration/resolve/#resolve-mainfields

Benedikt

**Comment by jamesncampbell** [comment]
The issue was that the react-on-rails creates a JS environment that more's like the browser. So, to enable SSR while using react-on-rails I had to use

```
const { createClient } = require('contentful/dist/contentful.browser.js)
```

which wasn't as obvious at first. Thank you so much for your help! This issue can be closed now

**Comment by jamesncampbell** [comment]
Actually. I might have been a bit hasty. Using the `contentful/dist/contentful.browser.js` brings back the original `window is undefined` error. 

Using the `contentful/dist/contentful.node.js` throws another error `Cannot read property 'fd' of undefined"` which seems to come from 

```
function useColors() {
  return 'colors' in exports.inspectOpts
    ? Boolean(exports.inspectOpts.colors)
    : tty.isatty(process.stderr.fd); <--- here
}

```

It seems like the rails JS environment created by react-on-rails just isn't robust enough to use the `contentful` package

**Comment by glemiere** [comment]
@jncampbell @axe312ger any news about this ? I have the same issue using Angular

**Comment by jncampbell** [comment]
@glemiere Unfortunately not. I ended up dropping the contentful package and using axios to make http calls to the content delivery API
